In [6]:
# Note: need to run the following in powershell
#       pip install polygon-api-client

import pandas as pd
from polygon import RESTClient
import requests

# Note: the furthest back we can go with the free plan seems to be exactly 2 years from the current date
key = 'TUo8bKPGXbU91jEOuI_Uus5EL73Q9rBC'
client = RESTClient(key)

In [7]:
from datetime import datetime, timezone
import time

# Note:  the API lists timestamps rather than dates.
#        These are unix millisecond timestamps, which describe the number of milliseconds 
#        since Jan 1, 1970, midnight UTC/GMT.
#        We use the following function to convert timestamps to date strings

def timestamp_to_date(timestamp):
    """
    Convert a UNIX timestamp in milliseconds to a date string in the format YYYY-MM-DD.
    """
    
    # Convert to seconds and shift by a day to align with data
    epoch_secs = timestamp/1000 + 86400
    
    # Convert the timestamp to a datetime object
    dt_object = datetime.fromtimestamp(epoch_secs)
    
    # Convert to string of form YYYY-MM-DD
    date_string = dt_object.strftime('%Y-%m-%d')
    
    return date_string

def date_to_timestamp(date):
    """
    Convert a string of the form YYYY-MM-DD to the timestamp of that day at 05:00:00
    """
    
    # Parse the input date string and set the time to 05:00:00
    date_obj = datetime.strptime(date, '%Y-%m-%d').replace(hour=5, minute=0, second=0, microsecond=0)
    
    # Calculate the UNIX timestamp in seconds (timezone-naive, assuming UTC)
    timestamp_seconds = (date_obj - datetime(1970, 1, 1)).total_seconds()
    
    # Convert to milliseconds
    timestamp_milliseconds = int(timestamp_seconds * 1000)
    
    return timestamp_milliseconds

In [8]:
def multiple_stock_table(date):
    """
    Returns a dataframe containing all info on all stocks at a single specified date
    Date is a string of the form YYYY-MM-DD
    Dataframe is sorted by trade volume
    """
    
    # get data from API
    data = client.get_grouped_daily_aggs(date)

    # read into dataframe
    df = pd.DataFrame({
        'Close' : [stock.close for stock in data],
        'Volume': [stock.volume for stock in data],
        'Open' : [stock.open for stock in data],
        'High' : [stock.high for stock in data],
        'Low' : [stock.low for stock in data], 
        'Vwap': [stock.vwap for stock in data],
        'Transactions': [stock.transactions for stock in data]},
        index = [stock.ticker for stock in data])
    
    # sort by trading volume
    df = df.sort_values('Volume', ascending = False)
    
    return df

In [9]:
# Example of multiple stock table
# df = multiple_stock_table('2024-02-20')
# df

In [10]:
def single_stock_table(ticker, start_date, end_date):
    """
    Returns a dataframe containing all info on a given stock from start_date to end_date
    Dates are strings of the form YYYY-MM-DD
    """
    
    # get data from API
    data = client.get_aggs(ticker, 1, 'day', start_date, end_date)
    
    # read data into dataframe
    df = pd.DataFrame({
    'Timestamp' : [entry.timestamp for entry in data],
    'Date' : [timestamp_to_date(entry.timestamp) for entry in data],
    'Close' : [entry.close for entry in data],
    'Volume': [entry.volume for entry in data],
    'Open' : [entry.open for entry in data],
    'High' : [entry.high for entry in data],
    'Low' : [entry.low for entry in data], 
    'Vwap': [entry.vwap for entry in data],
    'Transactions': [entry.transactions for entry in data]}
    )
    
    return df

In [11]:
# Example of single_stock_table
# df = single_stock_table('NVDA', '2022-08-01', '2025-02-12')
# df

In [12]:
def exponential_smoothing(a, stock_data):
    """
    Applies exponential smoothing to each column (except timestamp and date) 
    of the dataframe
    0 < alpha < 1
    At alpha = 1, the smoothed data is equal to the initial data
    """
    stock_data[['Close', 'Volume', 'Open', 'High', 'Low']] = stock_data[['Close', 'Volume', 'Open', 'High', 'Low']].ewm(alpha = a, adjust = True).mean()
    return stock_data

In [13]:
# df = single_stock_table('NVDA', '2022-08-01', '2025-02-12')
# df = exponential_smoothing(0.3, df)
# df

In [14]:
def fetch_macd(stock_ticker, start_date, end_date, short_window = 12, long_window = 26, signal_window = 9):
    """
    Fetch MACD data from Polygon API for a given stock.

    If the MACD is higher than the signal line there is a upward trend and should think of buying 
    If the MACD is lower than the signal line there is a downwards trend and should think of selling
    
    start_date and end_date are strings of the form YYYY-MM-DD
    """
    
    # get data from API
    data = client.get_macd(stock_ticker, timespan = 'day', limit = 5000, adjusted = True, short_window = short_window, long_window = long_window, signal_window = signal_window, series_type = 'close', order = 'asc')

    # read data into dataframe
    df = pd.DataFrame({
    'Timestamp' : [entry.timestamp for entry in data.values],
    'Date' : [timestamp_to_date(entry.timestamp) for entry in data.values],   
    'MACD Value' : [entry.value for entry in data.values],
    'Signal' : [entry.signal for entry in data.values],
    })
    
    # filter by entries which are in the date range
    df = df[(df['Timestamp'] >= date_to_timestamp(start_date)) & (df['Timestamp'] <= date_to_timestamp(end_date))]
    
    return df

In [34]:
# Example of fetch_macd
macd_df = fetch_macd("AAPL", '2024-12-12', '2025-01-31')
macd_df

         Timestamp        Date  MACD Value    Signal
421  1733979600000  2024-12-12    5.071421  3.894034
422  1734066000000  2024-12-13    5.156619  4.146551
423  1734325200000  2024-12-16    5.396741  4.396589
424  1734411600000  2024-12-17    5.718013  4.660874
425  1734498000000  2024-12-18    5.471398  4.822978
426  1734584400000  2024-12-19    5.354631  4.929309
427  1734670800000  2024-12-20    5.577055  5.058858
428  1734930000000  2024-12-23    5.749985  5.197084
429  1735016400000  2024-12-24    6.053677  5.368402
430  1735189200000  2024-12-26    6.288037  5.552329
431  1735275600000  2024-12-27    6.126376  5.667138
432  1735534800000  2024-12-30    5.659475  5.665606
433  1735621200000  2024-12-31    5.087179  5.549920
434  1735794000000  2025-01-02    4.056723  5.251281
435  1735880400000  2025-01-03    3.164067  4.833838
436  1736139600000  2025-01-06    2.559461  4.378963
437  1736226000000  2025-01-07    1.834036  3.869977
438  1736312400000  2025-01-08    1.283870  3.352756
439  1736398800000  2025-01-09    0.838197  2.849844
440  1736485200000  2025-01-10    0.012805  2.282436
441  1736744400000  2025-01-13   -0.829458  1.660057
442  1736830800000  2025-01-14   -1.569242  1.014197
443  1736917200000  2025-01-15   -1.764809  0.458396
444  1737003600000  2025-01-16   -2.664528 -0.166189
445  1737090000000  2025-01-17   -3.201864 -0.773324
446  1737435600000  2025-01-21   -4.171891 -1.453037
447  1737522000000  2025-01-22   -4.789413 -2.120312
448  1737608400000  2025-01-23   -5.232207 -2.742691
449  1737694800000  2025-01-24   -5.589699 -3.312093
450  1737954000000  2025-01-27   -5.241299 -3.697934
451  1738040400000  2025-01-28   -4.238520 -3.806051
452  1738126800000  2025-01-29   -3.316816 -3.708204
453  1738213200000  2025-01-30   -2.698081 -3.506179
454  1738299600000  2025-01-31   -2.309407 -3.266825

In [16]:
def stock_proc(ticker, start_date, end_date, n):
    """
    Fetch stock data for a given ticker between start_date and end_date,
    and compute the Price Rate of Change (PROC) over the last 'n' days.
    Automatically fixes incorrect date order.
    """
    # Ensure correct date order
    start_date, end_date = min(start_date, end_date), max(start_date, end_date)

    # Fetch stock data from API
    data = client.get_aggs(ticker, 1, 'day', start_date, end_date)
    
    # Convert data into a DataFrame
    df = pd.DataFrame({
        'Close': [entry.close for entry in data],
        'Volume': [entry.volume for entry in data],
        'Open': [entry.open for entry in data],
        'High': [entry.high for entry in data],
        'Low': [entry.low for entry in data], 
        'Vwap': [entry.vwap for entry in data],
        'Transactions': [entry.transactions for entry in data]
    }, index=[timestamp_to_date(entry.timestamp) for entry in data])

    # Ensure data is sorted by date
    df.sort_index(inplace=True)
    
    # Compute PROC
    df["Close_n_days_ago"] = df["Close"].shift(n)  # Closing price 'n' days ago
    df["PROC"] = ((df["Close"] - df["Close_n_days_ago"]) / df["Close_n_days_ago"]) * 100
    
    # Get the latest row with valid PROC
    latest_data = df.iloc[-1][["Close", "Close_n_days_ago", "PROC"]]
    
    # Return the final DataFrame
    result = pd.DataFrame({
        "Ticker": [ticker],
        "Current Close": [latest_data["Close"]],
        f"Close {n} Days Ago": [latest_data["Close_n_days_ago"]],
        f"PROC ({n} days)": [latest_data["PROC"]]
    })
    
    return result

In [17]:
# df = stock_proc("NVDA", "2025-02-09", "2025-01-10", 10)
# df

In [18]:
def fetch_rsi(stock_ticker, start_date, end_date, timespan="day", window=14):
    """
    Fetches the Relative Strength Index (RSI) for a given stock ticker.
    RSI > 70 → Overbought (possible price decrease)
    RSI < 30 → Oversold (possible price increase)
    """
    
    # get data from API
    data = client.get_rsi(stock_ticker, window = window, timespan = 'day', limit = 5000, order = 'asc')

    # read data into dataframe
    df = pd.DataFrame({
    'Timestamp' : [entry.timestamp for entry in data.values],
    'Date' : [timestamp_to_date(entry.timestamp) for entry in data.values],
    'RSI Value' : [entry.value for entry in data.values]
    })
    
    # filter by entries which are in the date range
    df = df[(df['Timestamp'] >= date_to_timestamp(start_date)) & (df['Timestamp'] <= date_to_timestamp(end_date))]

    return df

In [19]:
# Example of fetch_rsi
# rsi_df = fetch_rsi("AAPL", '2024-12-12', '2025-01-31')
# rsi_df

In [20]:
def range_stock_data(start_date, end_date, stock_ticker):
    """
    Fetches historical stock data (High, Low, Close) over a date range.
    
    """
    data = client.get_aggs(
        ticker=stock_ticker,
        multiplier=1,
        timespan="day",
        from_=start_date,
        to=end_date,
        adjusted=True,
        sort="asc",
        limit=5000
    )

    df = pd.DataFrame({
        'Timestamp': [stock.timestamp for stock in data],
        'Close': [stock.close for stock in data],
        'Volume': [stock.volume for stock in data],
        'Open': [stock.open for stock in data],
        'High': [stock.high for stock in data],
        'Low': [stock.low for stock in data], 
        'Vwap': [stock.vwap for stock in data],
        'Transactions': [stock.transactions for stock in data]},
    )

    df["Timestamp"] = pd.to_datetime(df["Timestamp"], unit='ms')  # Convert timestamp to datetime
    df = df.sort_values('Timestamp', ascending=True)  # Sort data by time

    return df

In [21]:
# df = range_stock_data("2024-01-01", "2024-02-15", "AAPL")
# df

In [22]:
def calculate_williams_r(stock_data, window=14):
    """
    Calculates Williams %R for the given stock data.
    Above -20 → Sell signal
    Below -80 → Buy signal
    """
    
    # Calculate Williams %R using a rolling window
    stock_data["Williams %R"] = stock_data.apply(
        lambda row: (
            (max(stock_data.loc[row.name - window + 1: row.name, "High"]) - row["Close"]) /
            (max(stock_data.loc[row.name - window + 1: row.name, "High"]) - 
             min(stock_data.loc[row.name - window + 1: row.name, "Low"]))
        ) * -100 if row.name >= window - 1 else None, axis=1
    )

    return stock_data

In [43]:
# example of calculate_williams_r
# stock_data = single_stock_table("AAPL", "2024-01-01", "2024-02-15")
# df = calculate_williams_r(stock_data)
# df.dropna()

In [35]:
def calculate_KDJ(stock_data, window_k_raw = 9, window_d = 3, window_k_smooth = 3):
    """
    Calculates the KDJ indicators 
    """
    
    # Calculate RSV (i.e. raw %K)
    stock_data['H'] = stock_data['High'].rolling(window = window_k_raw).max()
    stock_data['L'] = stock_data['Low'].rolling(window = window_k_raw).min()

    stock_data['RSV'] = (
        (stock_data['Close'] - stock_data['L']) /
        (stock_data['H'] - stock_data['L'])
    ) * 100
    
    # Calculate %K by taking a moving average of RSV
    stock_data['%K'] = stock_data['RSV'].rolling(window = window_k_smooth).mean()
    
    # Calculate %D by taking a moving average of %K
    stock_data['%D'] = stock_data['%K'].rolling(window = window_d).mean()
    
    # Calculate %J by 
    stock_data['%J'] = 3 * stock_data['%K'] - 2 * stock_data['%D']
    
    # Omit intermediate columns
    stock_data = stock_data.drop(columns = ['H', 'L', 'RSV'])

    return stock_data

In [37]:
# example of calculate_KDJ
stock_data = single_stock_table("AAPL", "2024-01-01", "2024-02-15")
df = calculate_KDJ(stock_data)
# df.dropna()
df

,Timestamp,Date,Close,Volume,Open,High,Low,Vwap,Transactions,%K,%D,%J
0,1704171600000,2024-01-02,185.64,81964874.0,187.150,188.4400,183.8850,185.9465,1008871,NaN,NaN,NaN
1,1704258000000,2024-01-03,184.25,58414460.0,184.220,185.8800,183.4300,184.3226,656853,NaN,NaN,NaN
2,1704344400000,2024-01-04,181.91,71878670.0,182.150,183.0872,180.8800,182.0183,712692,NaN,NaN,NaN
3,1704430800000,2024-01-05,181.18,62371161.0,181.990,182.7600,180.1700,181.4740,682334,NaN,NaN,NaN
4,1704690000000,2024-01-08,185.56,59144470.0,182.085,185.6000,181.5000,184.3702,669173,NaN,NaN,NaN
5,1704776400000,2024-01-09,185.14,42841809.0,183.920,185.1500,182.7300,184.3706,538180,NaN,NaN,NaN
6,1704862800000,2024-01-10,186.19,46192908.0,184.350,186.4000,183.9200,185.2509,554777,NaN,NaN,NaN
7,1704949200000,2024-01-11,185.59,49128408.0,186.540,187.0500,183.6200,185.0604,584008,NaN,NaN,NaN
8,1705035600000,2024-01-12,185.92,40477782.0,186.060,186.7400,185.1900,185.8199,477050,NaN,NaN,NaN
9,1705381200000,2024-01-16,183.63,65076641.0,182.160,184.2600,180.9340,182.8866,767281,NaN,NaN,NaN
10,1705467600000,2024-01-17,182.68,47317433.0,181.270,182.9300,180.3000,181.9201,594632,52.100557,NaN,NaN
11,1705554000000,2024-01-18,188.63,77722754.0,186.090,189.1400,185.8300,187.9358,787233,60.362546,NaN,NaN
12,1705640400000,2024-01-19,191.56,68887985.0,189.330,191.9500,188.8200,190.6149,682663,75.816433,62.759845,101.929609
13,1705899600000,2024-01-22,193.89,60131852.0,192.300,195.3300,192.2600,193.9891,718107,93.795301,76.658093,128.069717
14,1705986000000,2024-01-23,195.18,42355590.0,195.020,195.7500,193.8299,194.8203,533093,94.460734,88.024156,107.333890
15,1706072400000,2024-01-24,194.50,53631316.0,195.420,196.3800,194.3400,195.2063,594714,91.679433,93.311823,88.414654
16,1706158800000,2024-01-25,194.17,54822126.0,195.220,196.2675,193.1125,194.7337,644526,90.291785,92.143984,86.587388
17,1706245200000,2024-01-26,192.42,44587111.0,194.270,194.7600,191.9400,193.1207,534165,83.312604,88.427941,73.081930
18,1706504400000,2024-01-29,191.73,47145622.0,192.010,192.2000,189.5800,191.2954,599513,77.570481,83.724957,65.261529
19,1706590800000,2024-01-30,188.04,55836970.0,190.940,191.8000,187.4700,188.7927,690705,55.801030,72.228038,22.947015
20,1706677200000,2024-01-31,184.40,55467803.0,187.040,187.0950,184.3500,185.3525,679844,30.815195,54.728902,-17.012220
21,1706763600000,2024-02-01,186.86,64885408.0,183.985,186.9500,183.8200,185.5688,820977,15.189106,33.935110,-22.302904
22,1706850000000,2024-02-02,185.85,102527680.0,179.860,187.3300,179.2500,184.7440,1108465,21.049449,22.351250,18.445847
23,1707109200000,2024-02-05,187.68,69654320.0,188.150,189.2500,185.8400,187.6824,804748,37.314876,24.517810,62.909007
24,1707195600000,2024-02-06,189.30,43490759.0,186.860,189.3100,186.7695,188.4788,530825,48.932553,35.765626,75.266407
25,1707282000000,2024-02-07,189.41,53438955.0,190.640,191.0500,188.6100,189.3803,596088,57.924962,48.057464,77.659960
26,1707368400000,2024-02-08,188.32,40962046.0,189.385,189.5350,187.3500,188.3032,521464,64.867196,57.241570,80.118447
27,1707454800000,2024-02-09,188.85,45155216.0,188.650,189.9900,188.0000,189.0056,544714,70.679586,64.490582,83.057596
28,1707714000000,2024-02-12,187.15,41781934.0,188.415,188.6700,186.7900,187.5914,585515,71.160595,68.902459,75.676868
29,1707800400000,2024-02-13,185.04,56529529.0,185.770,186.2100,183.5128,185.0421,644015,64.170324,68.670169,55.170636
30,1707886800000,2024-02-14,184.15,54617917.0,185.320,185.5300,182.4400,183.6207,679072,52.514124,62.615015,32.312343
31,1707973200000,2024-02-15,183.86,65434496.0,183.550,184.4900,181.3500,182.8487,756083,38.823170,51.835873,12.797763

In [26]:
def get_all_features(ticker, start_date, end_date, alpha = 0.8, smoothing = True,
                     macd_short_window = 12, macd_long_window = 26, macd_signal_window = 9, 
                     rsi_timespan = 'day', rsi_window=14,
                     williams_r_window = 14, 
                     window_k_raw = 9, window_d = 3, window_k_smooth = 3):
    """
    Returns a data frame with all stock info and indicators
        :param ticker: The ticker symbol for the stock",
        :param start_date: A string of the form YYYY-MM-DD, earliest date to pull data from,
        :param end_date: A string of the form YYYY-MM-DD, latest date to pull data from,
        :param alpha: The parameter for exponential smoothing,
        :param smoothing: Specifies whether or not to apply exponential smoothing to raw data
        :param macd_short_window: The short window size used to compute MACD,
        :param macd_long_window: The long window size used to compute MACD,
        :param macd_signal_window: The window size used to calculate signal line,
        :param rsi_timespan: The size of underlying aggregate time window when computing RSI,
        :param rsi_window: The window size used to calculate the simple moving average for RSI,
        :param williams_r_window: The window size used to calculate the Williams %R,
        :param window_k_raw: The window size used to compute the raw %K,
        :param window_d: The window size used of the moving average used to compute %D,
        :param window_k_smooth: The window size of the moving average used to compute smooth %K,
    """
    
    # get close, vol, open, high, low, vwap, and transactions
    basic_data = single_stock_table(ticker, start_date, end_date)
    
    # exponentially smooth data
    if smoothing:
        basic_data = exponential_smoothing(alpha, basic_data)
    
    # get macd and signal
    macd_data = fetch_macd(ticker, start_date, end_date, macd_short_window, macd_long_window, macd_signal_window)
    
    # get rsi
    rsi_data = fetch_rsi(ticker, start_date, end_date, rsi_timespan, rsi_window)
    
    # merge basic and macd by inner joining along timestamps and dates
    df = pd.merge(basic_data, macd_data, how = 'inner', on = ['Timestamp', 'Date', 'Timestamp', 'Date'])
    
    # merge with rsi by inner joining along timestamps and dates
    df = pd.merge(df, rsi_data, how = 'inner', on = ['Timestamp', 'Date', 'Timestamp', 'Date'])
    
    # compute Williams%R and KDJ indicators
    df = calculate_williams_r(calculate_KDJ(df))
    
    # returns final dataframe excluding rows with N/A entries
    return df.dropna().reset_index(drop = True)

In [38]:
# Example of get_all_features
# df = get_all_features('AAPL', '2022-01-01', '2025-02-21', 0.8)
# df

,Timestamp,Date,Close,Volume,Open,High,Low,Vwap,Transactions,MACD Value,Signal,RSI Value,%K,%D,%J,Williams %R
0,1682913600000,2023-05-01,169.520518,5.322847e+07,168.976291,170.253647,168.362887,169.6586,540745,2.498291,2.408493,66.492875,92.445760,70.295370,136.746539,-7.097887
1,1683000000000,2023-05-02,168.736104,4.938625e+07,169.867258,170.330729,167.704577,168.6978,509755,2.486738,2.424142,62.971361,88.219082,82.907728,98.841790,-17.314507
2,1683086400000,2023-05-03,167.707221,6.197885e+07,169.573452,170.802146,167.268915,169.0130,610052,2.362397,2.411793,59.451396,76.161068,85.608636,57.265930,-39.661972
3,1683172800000,2023-05-04,166.173444,7.737631e+07,165.826690,167.792429,164.901783,166.0983,832121,2.105634,2.350561,54.458768,59.757043,74.712398,29.846335,-59.317570
4,1683259200000,2023-05-05,172.090689,1.061976e+08,169.945338,172.998486,169.588357,173.3116,915977,2.501098,2.380669,68.015674,63.980707,66.632939,58.676243,-9.078337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,1739509200000,2025-02-14,243.757989,4.083663e+07,240.132642,244.672579,239.688702,244.0513,481651,0.069776,-1.651815,60.576062,78.966289,53.673083,129.552702,-11.026233
451,1739854800000,2025-02-18,244.327598,4.098156e+07,243.346528,245.078516,241.409740,244.0795,486627,0.780039,-1.165445,60.393764,95.092466,76.640042,131.997313,-8.038864
452,1739941200000,2025-02-19,244.761520,3.206898e+07,244.397306,245.823703,242.810268,244.6718,383364,1.359533,-0.660449,60.784818,94.972116,89.676957,105.562434,-5.763119
453,1740027600000,2025-02-20,245.616304,3.007162e+07,244.831461,246.588741,243.994054,245.6205,405675,1.874640,-0.153431,61.760659,94.995076,95.019886,94.945455,-4.912390
454,1740114000000,2025-02-21,245.563261,4.722470e+07,245.726292,248.269748,244.974811,246.4026,508280,2.234514,0.324158,61.281669,92.098384,94.021859,88.251435,-12.602028