In [25]:
#in terminal run:
#pip install yahoo_fin
#pip install requests_html

In [3]:
from yahoo_fin.stock_info import get_data
import requests
import pandas as pd

Warning - Certain functionality
             requires requests_html, which is not installed.

             Install using:
             pip install requests_html

             After installation, you may have to restart your Python session.

In [4]:
#Example of get_data
#Gets all of the historic data available for Amazon with a weekly interval between the two dates
#Data is returned in a pandas dataframe
amazon_weekly = get_data('amzn',
                         start_date='12/04/2009',
                         end_date='02/18/2025',
                         index_as_date = True,
                         interval='1wk')
amazon_weekly

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [28]:
def data_for_multiple_tickers(ticker_list,
                              start_date,
                              end_date,
                              index_as_date = True,
                              interval = '1wk'):
    
    '''
    A function to get historical data for multiple tickers at once.
    
    ticker_list is a list of tickers (strings)
    start_date & end_date are MM/DD/YYYY strings
    index_as_date bool
    interval can be '1d', '1wk', '1mo'
    
    Returns a dictionary of pandas dataframes for each ticker
    '''
    
    historical_datas = {}
    
    for ticker in ticker_list:
        df = get_data(ticker,
                      start_date,
                      end_date,
                      index_as_date,
                      interval)
        
        historical_datas[ticker] = df
        
    return historical_datas

In [32]:
#Example: 
list1 = ['amzn', 'aapl', 'ba']
dict_of_hist_data = data_for_multiple_tickers(ticker_list = list1,
                              start_date='12/04/2009',
                              end_date='12/04/2019')
dict_of_hist_data

{'amzn':                  open       high        low      close   adjclose     volume  \
 2009-11-30   7.181000   7.295500   6.755500   6.879000   6.879000  627018000
 2009-12-07   6.900000   6.950000   6.491000   6.707500   6.707500  957260000
 2009-12-14   6.625000   6.630500   6.282500   6.424000   6.424000  915898000
 2009-12-21   6.524000   6.985000   6.509500   6.923500   6.923500  648120000
 2009-12-28   6.987500   7.129000   6.726000   6.726000   6.726000  572014000
 ...               ...        ...        ...        ...        ...        ...
 2019-11-04  90.050499  90.752998  88.702003  89.293999  89.293999  229232000
 2019-11-11  88.900002  89.310997  86.642998  86.974503  86.974503  263310000
 2019-11-18  86.915001  88.125999  86.135498  87.286003  87.286003  260846000
 2019-11-25  87.662498  91.234497  87.662003  90.040001  90.040001  232328000
 2019-12-02  90.220001  90.277496  87.361504  88.498001  88.498001  146130000

            ticker
 2009-11-30   AMZN
 2009-12-07   AMZN
 2009-12-14   AMZN
 2009-12-21   AMZN
 2009-12-28   AMZN
 ...           ...
 2019-11-04   AMZN
 2019-11-11   AMZN
 2019-11-18   AMZN
 2019-11-25   AMZN
 2019-12-02   AMZN

 [523 rows x 7 columns],
 'aapl':                  open       high        low      close   adjclose      volume  \
 2009-11-30   7.050714   7.138571   6.795714   6.904286   5.817695  1275604400
 2009-12-07   6.904286   7.132143   6.738571   6.952500   5.858321  3009384000
 2009-12-14   6.977500   7.053929   6.821429   6.979643   5.881193  2265844000
 2009-12-21   7.001786   7.476786   6.988214   7.465714   6.290767  1807836800
 2009-12-28   7.561429   7.641071   7.439643   7.526071   6.341625  1854266400
 ...               ...        ...        ...        ...        ...         ...
 2019-11-04  64.332497  65.110001  63.842499  65.035004  62.792530   423960800
 2019-11-11  64.574997  66.445000  64.570000  66.440002  64.341690   461333600
 2019-11-18  66.449997  67.000000  65.099998  65.445000  63.378094   455825200
 2019-11-25  65.677498  67.000000  65.625000  66.812500  64.702423   301081200
 2019-12-02  66.817497  67.062500  64.072502  64.862503  62.813995   208917600

            ticker
 2009-11-30   AAPL
 2009-12-07   AAPL
 2009-12-14   AAPL
 2009-12-21   AAPL
 2009-12-28   AAPL
 ...           ...
 2019-11-04   AAPL
 2019-11-11   AAPL
 2019-11-18   AAPL
 2019-11-25   AAPL
 2019-12-02   AAPL

 [523 rows x 7 columns],
 'ba':                   open        high         low       close    adjclose  \
 2009-11-30   53.990002   55.450001   53.509998   54.680000   42.608692
 2009-12-07   55.200001   56.389999   54.720001   55.599998   43.325596
 2009-12-14   56.020000   56.560001   53.099998   53.439999   41.642429
 2009-12-21   53.360001   55.650002   53.360001   55.480000   43.232079
 2009-12-28   55.330002   55.549999   54.049999   54.130001   42.180119
 ...                ...         ...         ...         ...         ...
 2019-11-04  346.459991  361.609985  346.049988  351.000000  346.899567
 2019-11-11  349.040009  373.480011  345.559998  371.679993  369.481689
 2019-11-18  371.670013  375.600006  361.609985  371.339996  369.143707
 2019-11-25  372.519989  374.769989  366.179993  366.179993  364.014221
 2019-12-02  367.079987  367.380005  347.609985  352.079987  349.997620

               volume ticker
 2009-11-30   9447500     BA
 2009-12-07  26659600     BA
 2009-12-14  34743900     BA
 2009-12-21  11391500     BA
 2009-12-28   8886600     BA
 ...              ...    ...
 2019-11-04  19040300     BA
 2019-11-11  31539500     BA
 2019-11-18  20888300     BA
 2019-11-25  11719300     BA
 2019-12-02   9478000     BA

 [523 rows x 7 columns]}

In [33]:
#We can still get data for a specific ticker by just looking it up in the dictionary
dict_of_hist_data['aapl']

,open,high,low,close,adjclose,volume,ticker
2009-11-30,7.050714,7.138571,6.795714,6.904286,5.817695,1275604400,AAPL
2009-12-07,6.904286,7.132143,6.738571,6.952500,5.858321,3009384000,AAPL
2009-12-14,6.977500,7.053929,6.821429,6.979643,5.881193,2265844000,AAPL
2009-12-21,7.001786,7.476786,6.988214,7.465714,6.290767,1807836800,AAPL
2009-12-28,7.561429,7.641071,7.439643,7.526071,6.341625,1854266400,AAPL
...,...,...,...,...,...,...,...
2019-11-04,64.332497,65.110001,63.842499,65.035004,62.792530,423960800,AAPL
2019-11-11,64.574997,66.445000,64.570000,66.440002,64.341690,461333600,AAPL
2019-11-18,66.449997,67.000000,65.099998,65.445000,63.378094,455825200,AAPL
2019-11-25,65.677498,67.000000,65.625000,66.812500,64.702423,301081200,AAPL
2019-12-02,66.817497,67.062500,64.072502,64.862503,62.813995,208917600,AAPL